import Axios from 'axios';
import Head from 'next/head';
import { useState, useCallback } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [cardNumber, setCardNumber] = useState('');
  const [expirationDate, setExpirationDate] = useState('');
  const [cvc, setCvc] = useState('');

  const handleSubmit = useCallback(
    async (event) => {
      event.preventDefault();

      const { data: token } = await Axios.post('/api/token', {
        card: {
          number: cardNumber,
          exp_month: expirationDate.split('/')[0],
          exp_year: expirationDate.split('/')[1],
          cvc,
        },
      });

      await Axios.post('/api/charge', {
        token: token.id,
      });
    },
    [cardNumber, expirationDate, cvc]
  );

  return (
    <form className={styles.container} onSubmit={handleSubmit}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.card}>
        <div>
          <div className={styles.priceCard}>
            <h3>De 1000,00</h3>
            <h3>Por 500,00</h3>
          </div>

          <div>
            <span>Número do cartão</span>
            <div>
              <input
                placeholder="1234 1234 1234 1234"
                className={styles.input}
                type="number"
                value={cardNumber}
                onChange={(e) => setCardNumber(e.target.value)}
              />
            </div>
          </div>

          <div>
            <span>Data de expiração</span>
            <div>
              <input
                placeholder="MM/YYYY"
                className={styles.input}
                value={expirationDate}
                onChange={(e) => setExpirationDate(e.target.value)}
              />
            </div>
          </div>

          <div>
            <span>CVC</span>
            <div>
              <input
                placeholder="123"
                className={styles.input}
                value={cvc}
                onChange={(e) => setCvc(e.target.value)}
              />
            </div>
            <button className={styles.button} type="submit">
              Comprar
            </button>
          </div>
        </div>
      </div>
    </form>
  );
}
